#4 fix a lot of test errors caused by runtime exceptions in fest-assert.
fest-assert:1.4 has a dependency problem and therefore throws some
NoSuchMethodErrors at runtime. Falling back to 1.3 fixes that issue.